In [2]:
import pandas as pd
import numpy as np

In [4]:
#1)using the array function
array_1 = np.array([1,2,3,4,5,6,7,8,9,10])
array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
#2)adddition of arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
result


array([5, 7, 9])

In [89]:
#3)slicing an array
arr = np.array([0, 1, 2, 3, 4, 5])
sliced_arr = arr[2:5]
sliced_arr 

array([2, 3, 4])

In [90]:
#4)Reshaping an Array
arr3 = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr3.reshape(2, 3)
reshaped_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
#5)Finding the Minimum value of an array
array_1 = np.array([1,2,3,4,5,6,7,8,9,10])
min_val = np.min(array_1)
min_val

1

In [92]:
#6)using the mean function to get the mean of the array
array_1 = np.array([1,2,3,4,5,6,7,8,9,10])
array_mean = np.mean(array_1)
print("The array mean is :",array_mean)

The array mean is : 5.5


In [93]:
#7)using the std function to get the standard deviation of the arrays 
array_1 = np.array([1,2,3,4,5,6,7,8,9,10])
array_std = np.std(array_1)
array_std

2.8722813232690143

In [94]:
#8)using the clipp function to clipp between the array values
array_1 = np.array([1,2,3,4,5,6,7,8,9,10])
clipped_array = np.clip(array_1,3,6)
clipped_array

array([3, 3, 3, 4, 5, 6, 6, 6, 6, 6])

In [95]:
#9)using the union1d function to get the union between sets of array
array_1 = np.array([1,2,9,4,5,6,11,8,9,16])
array_2 = np.array([1,2,3,11,5,12,7,9,9,15])
array_union = np.union1d(array_1,array_2)
array_union

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 15, 16])

In [96]:
#10)using the intersection1d function to get the union between sets of array
array_1 = np.array([1,2,9,4,5,6,11,8,9,16])
array_2 = np.array([1,2,3,11,5,12,7,9,9,15])
array_intersection =np.intersect1d(array_1,array_2)
array_intersection

array([ 1,  2,  5,  9, 11])

In [98]:
#11)using the max() function to find the maximum value of an array
array_1 = np.array([1,2,3,4,5,6,7,8,9,10])
max_val = max(array_1)
max_val

10

In [99]:
#12) using the sort function to sort the array
array_1 = np.array([1,2,9,4,5,6,11,8,9,16])
sort_array= np.sort(array_1)
sort_array

array([ 1,  2,  4,  5,  6,  8,  9,  9, 11, 16])

In [100]:
#13)using the vstack function to concatenate the array vertically
array_1 = np.array([1,2,9,4,5,6,11,8,9,16])
#Concatenate arrays vertically
concatenate_array_vertically =np.vstack(array_1)
concatenate_array_vertically

array([[ 1],
       [ 2],
       [ 9],
       [ 4],
       [ 5],
       [ 6],
       [11],
       [ 8],
       [ 9],
       [16]])

In [101]:
#14)using the vstack function to concatenate the array horizontally
array_1 = np.array([1, 2, 9, 4, 5, 6, 11, 8, 9, 16])
array_2 = np.array([1, 2, 3, 11, 5, 12, 7, 9, 9, 15])

# Convert 1-dimensional arrays to 2-dimensional arrays
array_1_2d = array_1.reshape(-1, 1)
array_2_2d = array_2.reshape(-1, 1)

# Concatenate arrays horizontally
concatenate_array_vertically = np.hstack((array_1_2d, array_2_2d))
print(concatenate_array_vertically)


[[ 1  1]
 [ 2  2]
 [ 9  3]
 [ 4 11]
 [ 5  5]
 [ 6 12]
 [11  7]
 [ 8  9]
 [ 9  9]
 [16 15]]


In [102]:
#15)usind the random function to get the random numbers
random_numbers = np.random.randn(6)
random_numbers

array([ 0.86500368, -1.60201637,  0.96181359, -0.33803791, -0.61069869,
        1.67876426])

In [103]:
#15)Concatenating Arrays
array_1 = np.array([1, 2, 9, 4, 5, 6, 11, 8, 9, 16])
array_2 = np.array([1, 2, 3, 11, 5, 12, 7, 9, 9, 15])
concatenated_arr = np.concatenate((array_1, array_2))
concatenated_arr

array([ 1,  2,  9,  4,  5,  6, 11,  8,  9, 16,  1,  2,  3, 11,  5, 12,  7,
        9,  9, 15])

In [104]:
#16) Linear Algebra - Dot Product
array_1 = np.array([1, 2, 9, 4, 5, 6, 11, 8, 9, 16])
array_2 = np.array([1, 2, 3, 11, 5, 12, 7, 9, 9, 15])
dot_product = np.dot(array_1, array_2)
dot_product

643

In [105]:
#17)Applying a Function Element-wise
array_1 = np.array([1, 2, 9, 4, 5, 6, 11, 8, 9, 16])
squared_arr = np.square(array_1)
squared_arr

array([  1,   4,  81,  16,  25,  36, 121,  64,  81, 256], dtype=int32)

In [106]:
#)18)Element-wise Comparison
array_1 = np.array([1, 2, 9, 4, 5, 6, 11, 8, 9, 16])
array_2 = np.array([1, 2, 3, 11, 5, 12, 7, 9, 9, 15])
comparison_result = array_1 > array_2
comparison_result

array([False, False,  True, False, False, False,  True, False, False,
        True])

In [107]:
#19)Creating a Range of Values
range_arr = np.arange(1, 10, 2)
range_arr 

array([1, 3, 5, 7, 9])

In [109]:
#20)Transposing a Matrix
matrix = np.array([[1, 2], [3, 4]])
transposed_matrix = matrix.T
transposed_matrix

array([[1, 3],
       [2, 4]])

In [110]:
#21) Creating an Identity Matrix
identity_matrix = np.eye(3)
identity_matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [111]:
#22)Element-wise Exponential
array_1 = np.array([1, 2, 9, 4, 5, 6, 11, 8, 9, 16])
exponential_arr = np.exp(array_1)
exponential_arr

array([2.71828183e+00, 7.38905610e+00, 8.10308393e+03, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 5.98741417e+04, 2.98095799e+03,
       8.10308393e+03, 8.88611052e+06])

In [112]:
#23)Element-wise Logarithm
array_1 = np.array([1, 2, 9, 4, 5, 6, 11, 8, 9, 16])
log_arr = np.log(array_1)
log_arr 

array([0.        , 0.69314718, 2.19722458, 1.38629436, 1.60943791,
       1.79175947, 2.39789527, 2.07944154, 2.19722458, 2.77258872])

In [113]:
#24)Finding Unique Elements
arr5 = np.array([1, 2, 3, 1, 2, 4, 5])
unique_elements = np.unique(arr5)
unique_elements 

array([1, 2, 3, 4, 5])

In [114]:
#25)Filling an Array with a Specific Value
array_1 = np.array([1, 2, 9, 4, 5, 6, 11, 8, 9, 16])
filled_arr = np.full_like(array_1, fill_value=10)
filled_arr

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [115]:
#26)Computing the Cumulative Sum
array_1 = np.array([1, 2, 9, 4, 5, 6, 11, 8, 9, 16])
cumulative_sum = np.cumsum(array_1)
cumulative_sum 

array([ 1,  3, 12, 16, 21, 27, 38, 46, 55, 71], dtype=int32)

In [117]:
#27)Finding the Index of the Maximum Value
array_1 = np.array([1, 2, 9, 4, 5, 6, 11, 8, 9, 16])
max_index = np.argmax(array_1)
max_index

9

In [118]:
#28)Generating a Diagonal Matrix
diagonal_matrix = np.diag([1, 2, 3])
diagonal_matrix

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [120]:
#29)Reversing an Array
array_1 = np.array([1, 2, 9, 4, 5, 6, 11, 8, 9, 16])
reversed_arr = np.flip(array_1)
reversed_arr 

array([16,  9,  8, 11,  6,  5,  4,  9,  2,  1])

In [121]:
#30)Element-wise Absolute Value
array_1 = np.array([1, 2, 9, 4, 5, 6, 11, 8, 9, 16])
array_2 = np.array([1, 2, 3, 11, 5, 12, 7, 9, 9, 15])
abs_arr = np.abs(array_1 - array_2)
abs_arr

array([0, 0, 6, 7, 0, 6, 4, 1, 0, 1])